name: mediverse_patient_app
description: MediVerse Patient Queue Tracking App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Networking
  dio: ^5.4.0

  # Local Notifications
  flutter_local_notifications: ^16.3.0

  # WebSocket
  web_socket_channel: ^2.4.0

  # UI Enhancement
  flutter_screenutil: ^5.9.0
  intl: ^0.18.1

  # Local Storage
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # لو عندك خط Cairo حطه هنا
  # fonts:
  #   - family: Cairo
  #     fonts:
  #       - asset: assets/fonts/Cairo-Regular.ttf
  #       - asset: assets/fonts/Cairo-Bold.ttf
  #         weight: 700
